// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Category struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
}

type Course struct {
	ID          uuid.UUID
	CategoryID  uuid.UUID
	Name        string
	Description sql.NullString
	Price       string
}
